version: '3.8'

services:

  frontend:
    image: y4r1k/taxi-frontend:latest
    ports:
      - "3001:3001"
    volumes:
      - frontend_build:/app/result_build/
    environment:
      NODE_ENV: production
    restart: always

  backend:
    image: y4r1k/taxi-backend:latest
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/ssl/frantsuz.crt:/etc/nginx/frantsuz.crt
#      - ./nginx/ssl/frantsuz.key:/etc/nginx/frantsuz.key
      - frontend_build:/usr/share/nginx/html/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  static_value:
  media_value:
